MvcProjeKampiDeneme/Controllers/ContentController.cs
using MvcProjeKampiDeneme.BLL.Abstract;
using MvcProjeKampiDeneme.BLL.DependencyResolvers.Ninject;
using MvcProjeKampiDeneme.Entity.Concrete;
using MvcProjeKampiDeneme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampiDeneme.Controllers
{
    public class ContentController : Controller
    {
        // GET: Content
        private IContentService _contentService;
        private IWriterService _writerService;
        public ContentController()
        {
            _contentService = InstanceFactory.GetInstance<IContentService>();
            _writerService = InstanceFactory.GetInstance<IWriterService>();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllContentBySearch(string p)
        {
            if (!string.IsNullOrEmpty(p))
            {
                var contentValues = _contentService.GetAllBySearch(p);
                return View(contentValues);
            }

            return View(_contentService.GetAll());
        }

        public ActionResult ContentByHeading(int id)
        {
            List<Content> contents = _contentService.GetAll();
            List<Writer> writers = _writerService.GetAll();

            var record = from w in writers
                         join c in contents on w.WriterID equals c.WriterID
                         where c.HeadingID == id
                         select new WriterContent
                         {
                             Content = c,
                             Writer = w
                         };


            return View(record);
        }
    }
}

MvcProjeKampiDeneme/Views/Content/ContentByHeading.cshtml
@using MvcProjeKampiDeneme.Entity.Concrete
@model IEnumerable<MvcProjeKampiDeneme.Models.WriterContent>

@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- /.tab-pane -->
                <!-- The timeline -->
                <div class="timeline">
                    @foreach (var item in Model)
                    {

                        <!-- timeline time label -->
                        <div class="time-label">
                            <span class="bg-success">
                                @item.Content.ContentDate.ToShortDateString()
                            </span>
                        </div>
                        <div>
                            <i class="fas fa-comments bg-warning"></i>
                            <div class="timeline-item">
                                <span class="time"></span>

                                <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a></h3>

                                <div class="timeline-body">
                                    @item.Content.ContentValue
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

MvcProjeKampiDeneme/Views/Content/GetAllContentBySearch.cshtml
@using MvcProjeKampiDeneme.Entity.Concrete
@model List<Content>


@{
    ViewBag.Title = "GetAllContentBySearch";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using(Html.BeginForm("GetAllContentBySearch","Content",FormMethod.Post))
{
    <p>
        Aranacak Kelimeyi girin:@Html.TextBox("p")
        <input class="btn btn-secondary" type="submit" value="Ara" />
    </p>
}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- /.tab-pane -->
                <!-- The timeline -->
                <div class="timeline">
                    @foreach (var item in Model)
                    {

                        <!-- timeline time label -->
                        <div class="time-label">
                            <span class="bg-success">
                                @item.ContentDate.ToShortDateString()
                            </span>
                        </div>
                        <div>
                            <i class="fas fa-comments bg-warning"></i>
                            <div class="timeline-item">
                                <span class="time"></span>

                                <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a></h3>

                                <div class="timeline-body">
                                    @item.ContentValue
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>