MvcProjeKampiDeneme/Controllers/AuthorizationController.cs
using MvcProjeKampiDeneme.BLL.Abstract;
using MvcProjeKampiDeneme.BLL.DependencyResolvers.Ninject;
using MvcProjeKampiDeneme.Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampiDeneme.Controllers
{
    public class AuthorizationController : Controller
    {
        // GET: Authorization
        private IAdminService _adminService;

        public AuthorizationController()
        {
            _adminService = InstanceFactory.GetInstance<IAdminService>();
        }

        public ActionResult Index()
        {
            var values = _adminService.GetAll();
            return View(values);
        }
        [HttpGet]
        public ActionResult AdminAdd()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult AdminAdd(Admin admin)
        {
            _adminService.Add(admin);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateAdmin(int id)
        {
            var adminValue = _adminService.GetByID(id);
            return View(adminValue);
        }

        [HttpPost]
        public ActionResult UpdateAdmin(Admin admin)
        {
            _adminService.Update(admin);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampiDeneme/Views/Authorization/Index.cshtml
@using MvcProjeKampiDeneme.Entity.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Status</th>
        <th>Pasif Yap</th>
        <th>Yetkisini Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="#/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/UpdateAdmin/@item.AdminID" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>
<a href="#" class="btn btn-info">Yeni Admin Tanımla</a>

MvcProjeKampiDeneme/Views/Authorization/UpdateAdmin.cshtml
@using MvcProjeKampiDeneme.Entity.Concrete
@model MvcProjeKampiDeneme.Entity.Concrete.Admin
@{
    ViewBag.Title = "UpdateAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@using(Html.BeginForm("UpdateAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x=>x.AdminID,new {@class="form-control" })

        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class="form-control"})
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class="form-control"})
        <br />
        @Html.Label("Rol")
        @Html.TextBoxFor(x => x.AdminRole, new { @class="form-control"})
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}